[package]
name = "augmented-btrees"
version = "0.6.0"
description = "Contains implementations of BTree variants, most notable the B+Tree"
repository = "https://github.com/NatLabs/augmented-btrees"
license = "MIT"
keywords = ["b+tree", "data-structure", "sorted", "map"]

[dependencies]
base = "0.12.1"
buffer-deque = "0.1.0"
itertools = "0.2.1"

[dev-dependencies]
test = "2.0.0"
bench = "1.0.0"
fuzz = "0.2.1"
stableheapbtreemap = "1.5.0"
map = "9.0.1"

[toolchain]
moc = "0.11.1"
